services:

  traefik:
    image: traefik:v3
    container_name: traefik
    restart: always
    deploy:
      resources:
        limits:
          memory: 512mb
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      - --entrypoints.websecure.address=:443
      - --api.dashboard=true
      - --api.insecure=false
      - --api.debug=false
      - --log.level=INFO
      - --accesslog=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=services
      - --providers.file.directory=/etc/traefik/dynamic
      - --providers.file.watch=true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.rule=Host(`proxy.home.arpa`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.services.api.loadbalancer.server.port=8080"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - services
      - gluetun
    volumes:
      - ./dynamic:/etc/traefik/dynamic:ro
      - ./secrets/certs:/certs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  gluetun:
    external: true
  services:
    external: true
