services:

  gluetun:
    image: qmcgaw/gluetun:v3
    container_name: gluetun
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512mb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qbit.entrypoints=websecure"
      - "traefik.http.routers.qbit.tls=true"
      - "traefik.http.routers.qbit.rule=Host(`downloads.home.arpa`)"
      - "traefik.http.services.qbit.loadbalancer.server.port=8080"
      - "traefik.docker.network=gluetun"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - '6881:6881'
      - '6881:6881/udp'
    networks:
      - gluetun
    env_file:
      - ./stack.env
    volumes:
      - gluetun-config:/gluetun

  qbit:
    image: linuxserver/qbittorrent:latest
    container_name: qbit
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512mb
    depends_on:
      - gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
      - DOCKER_MODS=ghcr.io/vuetorrent/vuetorrent-lsio-mod:latest
    network_mode: "service:gluetun"
    volumes:
      - qbit-config:/config
      - /mnt/media/Media:/downloads

networks:
  gluetun:
    external: true

volumes:
  gluetun-config:
    external: true
  qbit-config:
    external: true