services:
  arcane-agent:
    image: ghcr.io/getarcaneapp/agent:v2
    container_name: arcane-agent
    restart: unless-stopped
    labels:
      - "com.getarcaneapp.arcane.updater=true"
    env_file:
      - .env
    ports:
      - "3553:3553"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - arcane-data:/app/data

volumes:
  arcane-data: