services:

  traefik:
    image: traefik:v3
    container_name: traefik
    restart: always
    deploy:
      resources:
        limits:
          memory: 256mb
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      - --entrypoints.websecure.address=:443
      - --api.dashboard=false
      - --api.insecure=false
      - --api.debug=false
      - --log.level=INFO
      - --accesslog=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=immich
      - --providers.file.directory=/etc/traefik/dynamic
      - --providers.file.watch=true
      - --certificatesresolvers.vercel.acme.email=robert.harbul@gmail.com
      - --certificatesresolvers.vercel.acme.storage=/acme.json
      - --certificatesresolvers.vercel.acme.dnsChallenge.provider=vercel
    env_file:
      - stack.env
    ports:
      - "80:80"
      - "443:443"
    networks:
      - immich
    volumes:
      - ./dynamic:/etc/traefik/dynamic:ro
      - ./acme.json:/acme.json
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  immich:
    external: true